# Generated by Django 4.2.2 on 2023-07-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('Nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ip_nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='PaginaLocal',
        ),
    ]
